# Generated by Django 2.2.5 on 2020-02-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0003_auto_20191110_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='XP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_inicio', models.DateTimeField()),
                ('f_fin', models.DateTimeField()),
                ('id_xp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xp.XP')),
            ],
        ),
    ]
