# Generated by Django 3.0.3 on 2020-04-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='id_xp',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
