# Generated by Django 2.2.4 on 2019-11-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
