# Generated by Django 2.2.4 on 2019-11-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_sprint_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='sreview',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
