# Generated by Django 2.2.4 on 2019-11-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_sprint_sreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='sreview',
        ),
        migrations.CreateModel(
            name='Sreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=600)),
                ('id_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrum.Sprint')),
            ],
        ),
    ]
