# Generated by Django 2.2.4 on 2019-11-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0005_auto_20191111_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='id_pbacklog',
        ),
        migrations.AddField(
            model_name='sprint',
            name='id_pbacklog',
            field=models.ManyToManyField(blank=True, null=True, to='scrum.Pbacklog'),
        ),
    ]
