# Generated by Django 2.2.4 on 2019-11-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0006_auto_20191111_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='f_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='f_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
