# Generated by Django 2.2.4 on 2019-11-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_auto_20191111_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='id_srcrum',
            new_name='id_scrum',
        ),
    ]
