# Generated by Django 2.2.4 on 2019-11-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0008_auto_20191111_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='id_pbacklog',
            field=models.ManyToManyField(blank=True, to='scrum.Pbacklog'),
        ),
    ]
