# Generated by Django 2.2.4 on 2019-11-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0009_auto_20191114_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='id_pbacklog',
            field=models.ManyToManyField(to='scrum.Pbacklog'),
        ),
    ]
