# Generated by Django 2.2.4 on 2019-11-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0010_auto_20191115_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbacklog',
            name='estado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
