# Generated by Django 3.0.2 on 2020-01-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0014_auto_20191117_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymeeting',
            name='hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
