# Generated by Django 3.0.2 on 2020-01-17 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0015_dailymeeting_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymeeting',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
