# Generated by Django 2.2.5 on 2020-02-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xp', '0001_initial'),
        ('scrum', '0017_historiausuario_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiausuario',
            name='id_ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xp.Ciclo'),
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='id_xp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xp.XP'),
        ),
    ]
