# Generated by Django 3.0.3 on 2020-02-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0018_auto_20200206_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='sreview',
            name='id_pbacklog',
            field=models.ManyToManyField(blank=True, null=True, to='scrum.Pbacklog'),
        ),
    ]
