# Generated by Django 3.0.3 on 2020-03-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0021_sprint_confirmar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sreview',
            name='observaciones',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
