# Generated by Django 3.0.3 on 2020-04-11 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrum', '0023_historiausuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
