# Generated by Django 3.0.3 on 2020-04-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0024_auto_20200411_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbacklog',
            name='para',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pbacklog',
            name='quiero',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
