# Generated by Django 2.2.12 on 2020-05-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
